-- Migration 052: better-auth OAuth 2.1 authorization-server schema (BA-1, Mandrel task 17b5b863).
--
-- WHY THIS IS A STANDARD MIGRATION (was database/better-auth/001, promoted here):
-- the better-auth schema used to live OUTSIDE the migration runner
-- (database/better-auth/001-better-auth-oauth-schema.sql), applied only by a manual
-- step. That made it (a) un-portable in CI — ci.sh's disposable DB never had these
-- tables, so the BA-1 integration test could only pass against a hand-created scratch
-- DB — and (b) a manual prod step at OAuth-enable time. Promoting it to the standard
-- migrations/ runner means BOTH ci.sh's "migrate disposable DB" stage AND prod's
-- migration runner apply it automatically, so enabling OAuth needs only the
-- MANDREL_OAUTH_ENABLED env flag — no out-of-band schema step. Nothing loads the
-- old path at runtime (grep-verified: only the test referenced it), so this is a
-- clean lift with no runtime coupling.
--
-- GENERATED by `@better-auth/cli generate` against the BA-1 auth config
-- (better-auth 1.6.20 + @better-auth/oauth-provider 1.6.20 + jwt() plugin).
-- DO NOT hand-edit the table DDL below — regenerate from the auth config if the
-- plugins/config change, then re-run `bash scripts/schema-contract.sh regenerate`.
--
-- ADDITIVE ONLY (migration number 052 > BASELINE_THROUGH=42, so it runs on fresh
-- AND existing instances): every statement is CREATE TABLE / CREATE INDEX. It touches
-- NONE of the existing Mandrel tables. All 9 table names are NEW and do not collide with
-- any Mandrel table (Mandrel uses `sessions` PLURAL + `admin_users`; better-auth uses the
-- quoted SINGULAR `"session"` / `"user"`). Verified: zero collisions.
--
-- APPLIED AS THE APP DB ROLE: the migration runner (migrate.ts) connects as
-- DATABASE_USER (`mandrel` in prod, the throwaway role in tests) and runs this SQL,
-- so the tables are owned by the role the server connects as — exactly the ownership
-- the manual path documented.

create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "jwks" ("id" text not null primary key, "publicKey" text not null, "privateKey" text not null, "createdAt" timestamptz not null, "expiresAt" timestamptz);

create table "oauthClient" ("id" text not null primary key, "clientId" text not null unique, "clientSecret" text, "disabled" boolean, "skipConsent" boolean, "enableEndSession" boolean, "subjectType" text, "scopes" jsonb, "userId" text references "user" ("id") on delete cascade, "createdAt" timestamptz, "updatedAt" timestamptz, "name" text, "uri" text, "icon" text, "contacts" jsonb, "tos" text, "policy" text, "softwareId" text, "softwareVersion" text, "softwareStatement" text, "redirectUris" jsonb not null, "postLogoutRedirectUris" jsonb, "tokenEndpointAuthMethod" text, "grantTypes" jsonb, "responseTypes" jsonb, "public" boolean, "type" text, "requirePKCE" boolean, "referenceId" text, "metadata" jsonb);

create table "oauthRefreshToken" ("id" text not null primary key, "token" text not null unique, "clientId" text not null references "oauthClient" ("clientId") on delete cascade, "sessionId" text references "session" ("id") on delete set null, "userId" text not null references "user" ("id") on delete cascade, "referenceId" text, "expiresAt" timestamptz not null, "createdAt" timestamptz not null, "revoked" timestamptz, "authTime" timestamptz, "scopes" jsonb not null);

create table "oauthAccessToken" ("id" text not null primary key, "token" text not null unique, "clientId" text not null references "oauthClient" ("clientId") on delete cascade, "sessionId" text references "session" ("id") on delete set null, "userId" text references "user" ("id") on delete cascade, "referenceId" text, "refreshId" text references "oauthRefreshToken" ("id") on delete cascade, "expiresAt" timestamptz not null, "createdAt" timestamptz not null, "scopes" jsonb not null);

create table "oauthConsent" ("id" text not null primary key, "clientId" text not null references "oauthClient" ("clientId") on delete cascade, "userId" text references "user" ("id") on delete cascade, "referenceId" text, "scopes" jsonb not null, "createdAt" timestamptz not null, "updatedAt" timestamptz not null);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");

create index "oauthClient_userId_idx" on "oauthClient" ("userId");

create index "oauthRefreshToken_clientId_idx" on "oauthRefreshToken" ("clientId");

create index "oauthRefreshToken_sessionId_idx" on "oauthRefreshToken" ("sessionId");

create index "oauthRefreshToken_userId_idx" on "oauthRefreshToken" ("userId");

create index "oauthAccessToken_clientId_idx" on "oauthAccessToken" ("clientId");

create index "oauthAccessToken_sessionId_idx" on "oauthAccessToken" ("sessionId");

create index "oauthAccessToken_userId_idx" on "oauthAccessToken" ("userId");

create index "oauthAccessToken_refreshId_idx" on "oauthAccessToken" ("refreshId");

create index "oauthConsent_clientId_idx" on "oauthConsent" ("clientId");

create index "oauthConsent_userId_idx" on "oauthConsent" ("userId");
