#!/usr/bin/env bash
# provision-instance.sh — concierge provisioning of a dedicated Mandrel tester instance.
#
# Codifies the proven `brian` runbook: DNS gate -> secrets -> compose override ->
# stack up -> nginx vhost -> certbot -> instance admin -> connect doc -> smoke gate.
# Idempotent: safe to re-run; existing secrets/files are reused, not clobbered.
#
# USAGE:
#   scripts/provision-instance.sh <handle> <mcp_port> <pg_port> <redis_port> <backend_port> <frontend_port>
#
# Example:
#   scripts/provision-instance.sh neko-trappings 18082 15434 16381 15002 13002
#
# Per-customer artifacts (LOCAL only, never committed/pushed):
#   docker-compose.<h>.yml            (gitignored)
#   /root/.mandrel-<h>.env            (600)
#   /root/.mandrel-<h>-admin.env      (600)
#   /root/mandrel-handoffs/<h>-CONNECT.md (600)
#
# Constraints honored: only new compose projects (mandrel-<h>); prod (8080) and the
# mandrel-app / mandrel-brian stacks are never touched; `nginx -t` MUST pass before
# any reload; secrets are never printed.
set -euo pipefail

# ----- args ---------------------------------------------------------------------
if [[ $# -ne 6 ]]; then
  echo "usage: $0 <handle> <mcp_port> <pg_port> <redis_port> <backend_port> <frontend_port>" >&2
  exit 2
fi
H="$1"; MCP_PORT="$2"; PG_PORT="$3"; REDIS_PORT="$4"; BACKEND_PORT="$5"; FRONTEND_PORT="$6"

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOMAIN="${H}.mandrel.ridgetopai.net"
EXPECTED_IP="178.156.219.146"
ENV_FILE="/root/.mandrel-${H}.env"
ADMIN_ENV_FILE="/root/.mandrel-${H}-admin.env"
COMPOSE_OVERRIDE="${REPO_DIR}/docker-compose.${H}.yml"
NGINX_AVAIL="/etc/nginx/sites-available/${DOMAIN}"
NGINX_ENABLED="/etc/nginx/sites-enabled/${DOMAIN}"
HANDOFF_DIR="/root/mandrel-handoffs"
HANDOFF_DOC="${HANDOFF_DIR}/${H}-CONNECT.md"
TEMPLATE_DOC="${REPO_DIR}/docs/onboarding/CONNECT-MANDREL.md"
PROJECT="mandrel-${H}"

# Container DNS name -> port within the stack network is constant (8080/5432/6379/5000/3000).
log()  { echo "[$(date +%H:%M:%S)] [${H}] $*"; }
fail() { echo "[$(date +%H:%M:%S)] [${H}] FAILED: $*" >&2; exit 1; }

# ----- 1. DNS gate --------------------------------------------------------------
log "1/9 DNS gate: dig ${DOMAIN}"
GOT_IP="$(dig +short @1.1.1.1 "${DOMAIN}" 2>/dev/null | tail -1)"
if [[ "${GOT_IP}" != "${EXPECTED_IP}" ]]; then
  log "SKIP: DNS for ${DOMAIN} = '${GOT_IP:-<none>}', expected ${EXPECTED_IP}. Not provisioning."
  echo "RESULT:${H}:skipped-dns"
  exit 0
fi
log "DNS ok (${GOT_IP})"

# ----- 2. Secrets ---------------------------------------------------------------
if [[ -f "${ENV_FILE}" ]]; then
  log "2/9 secrets: ${ENV_FILE} exists, reusing"
else
  log "2/9 secrets: generating ${ENV_FILE}"
  MCP_AUTH_TOKEN="$(openssl rand -hex 32)"
  JWT_SECRET="$(openssl rand -hex 32)"
  umask 077
  cat > "${ENV_FILE}" <<EOF
MCP_AUTH_TOKEN=${MCP_AUTH_TOKEN}
JWT_SECRET=${JWT_SECRET}
MCP_ALLOWED_HOSTS=${DOMAIN},127.0.0.1:${MCP_PORT},localhost:${MCP_PORT}
EOF
  chmod 600 "${ENV_FILE}"
fi

# ----- 3. Compose override ------------------------------------------------------
log "3/9 compose override: ${COMPOSE_OVERRIDE}"
cat > "${COMPOSE_OVERRIDE}" <<EOF
# docker-compose.${H}.yml — override for ${DOMAIN}
# Dedicated founding-tester instance. Isolated stack (own names/ports/volumes/DB),
# built from main. Generated by scripts/provision-instance.sh.
#   docker compose -f docker-compose.yml -f docker-compose.${H}.yml \\
#     --env-file ${ENV_FILE} -p ${PROJECT} up -d --build \\
#     postgres redis mcp-server mandrel-command-backend mandrel-command-frontend
# Secrets in ${ENV_FILE} (600). nginx: / -> frontend:${FRONTEND_PORT}, /mcp -> mcp-server:${MCP_PORT}.
# LOCAL ONLY — gitignored (do not leak tester handles to the public repo).

services:
  postgres:
    container_name: mandrel-${H}-postgres
    ports: !override
      - "127.0.0.1:${PG_PORT}:5432"

  redis:
    container_name: mandrel-${H}-redis
    ports: !override
      - "127.0.0.1:${REDIS_PORT}:6379"

  mcp-server:
    container_name: mandrel-${H}-mcp-server
    ports: !override
      - "127.0.0.1:${MCP_PORT}:8080"
    environment:
      MCP_AUTH_TOKEN: "\${MCP_AUTH_TOKEN:?set MCP_AUTH_TOKEN in ${ENV_FILE}}"
      MCP_ALLOWED_HOSTS: "\${MCP_ALLOWED_HOSTS:-${DOMAIN}}"

  mandrel-command-backend:
    container_name: mandrel-${H}-command-backend
    ports: !override
      - "127.0.0.1:${BACKEND_PORT}:5000"
    environment:
      JWT_SECRET: "\${JWT_SECRET:?set JWT_SECRET in ${ENV_FILE}}"
      MANDREL_JWT_SECRET: "\${JWT_SECRET}"
      CORS_ORIGIN: "https://${DOMAIN}"
      FRONTEND_URL: "https://${DOMAIN}"
      MANDREL_MCP_URL: "http://mcp-server:8080"

  mandrel-command-frontend:
    container_name: mandrel-${H}-command-frontend
    ports: !override
      - "127.0.0.1:${FRONTEND_PORT}:3000"
EOF

# Ensure the per-customer compose file is gitignored (privacy).
GITIGNORE="${REPO_DIR}/.gitignore"
if ! grep -qxF "docker-compose.${H}.yml" "${GITIGNORE}" 2>/dev/null; then
  log "adding docker-compose.${H}.yml to .gitignore"
  printf 'docker-compose.%s.yml\n' "${H}" >> "${GITIGNORE}"
fi

# ----- 4. Up --------------------------------------------------------------------
log "4/9 stack up (-p ${PROJECT})"
docker compose -f "${REPO_DIR}/docker-compose.yml" -f "${COMPOSE_OVERRIDE}" \
  --env-file "${ENV_FILE}" -p "${PROJECT}" up -d --build \
  postgres redis mcp-server mandrel-command-backend mandrel-command-frontend

log "waiting for mcp-server /healthz 200 on 127.0.0.1:${MCP_PORT}"
ok=0
for i in $(seq 1 60); do
  code="$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:${MCP_PORT}/healthz" || true)"
  if [[ "${code}" == "200" ]]; then ok=1; break; fi
  sleep 3
done
[[ "${ok}" == "1" ]] || fail "mcp-server /healthz never returned 200 on port ${MCP_PORT}"
log "mcp-server healthy"

# ----- 5. nginx vhost -----------------------------------------------------------
log "5/9 nginx vhost: ${NGINX_AVAIL}"
# Pre-TLS vhost (port 80). certbot rewrites this in step 6 to add 443 + redirect.
cat > "${NGINX_AVAIL}" <<EOF
# ${DOMAIN} — founding-tester instance (generated by provision-instance.sh)
# / -> frontend (SPA + /api proxy), /mcp -> authenticated MCP transport. TLS by certbot.
server {
    server_name ${DOMAIN};
    client_max_body_size 25m;

    location = /mcp {
        proxy_pass http://127.0.0.1:${MCP_PORT}/mcp;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        chunked_transfer_encoding on;
    }

    location = /healthz {
        proxy_pass http://127.0.0.1:${MCP_PORT}/healthz;
        proxy_set_header Host \$host;
    }

    location / {
        proxy_pass http://127.0.0.1:${FRONTEND_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    listen 80;
}
EOF
ln -sf "${NGINX_AVAIL}" "${NGINX_ENABLED}"

log "nginx -t (must pass before reload)"
if ! nginx -t 2>/tmp/nginx-test-${H}.log; then
  cat "/tmp/nginx-test-${H}.log" >&2
  fail "nginx -t failed — NOT reloading (other vhosts untouched). Removing ${NGINX_ENABLED}."
fi
systemctl reload nginx
log "nginx reloaded"

# ----- 6. certbot ---------------------------------------------------------------
log "6/9 certbot --nginx -d ${DOMAIN}"
if [[ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]]; then
  log "cert already present, ensuring vhost has TLS (re-running certbot --nginx idempotently)"
fi
certbot --nginx -d "${DOMAIN}" --non-interactive --redirect --agree-tos \
  -m beaulieu08100@gmail.com
log "verifying nginx still valid after certbot"
nginx -t 2>/tmp/nginx-test-${H}-post.log || fail "nginx -t failed AFTER certbot"
systemctl reload nginx

# ----- 7. Create instance admin -------------------------------------------------
log "7/9 create instance admin (in-container bcrypt upsert)"
BACKEND_CONTAINER="mandrel-${H}-command-backend"
if [[ -f "${ADMIN_ENV_FILE}" ]]; then
  log "admin env exists; re-asserting admin row from stored password"
  ADMIN_PASSWORD="$(grep '^ADMIN_PASSWORD=' "${ADMIN_ENV_FILE}" | cut -d= -f2-)"
else
  ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | head -c 24)"
fi
ADMIN_USER="admin"
ADMIN_EMAIL="admin@${DOMAIN}"

# Generate bcrypt hash inside the backend container (native bcrypt, rounds=12 — matches
# what the login path verifies with). Hash is passed to psql via env, never printed.
HASH="$(docker exec -e PW="${ADMIN_PASSWORD}" "${BACKEND_CONTAINER}" \
  node -e 'const b=require("bcrypt");b.hash(process.env.PW,12).then(h=>process.stdout.write(h))')"
[[ -n "${HASH}" ]] || fail "bcrypt hash generation returned empty"

# Upsert via psql -v vars (values passed explicitly, never interpolated into shell).
# NOTE: -i is REQUIRED so the heredoc reaches psql's stdin inside the container.
docker exec -i "mandrel-${H}-postgres" psql -U mandrel -d mandrel -v ON_ERROR_STOP=1 -q \
  -v ADMIN_USER_V="${ADMIN_USER}" -v ADMIN_EMAIL_V="${ADMIN_EMAIL}" -v HASH_V="${HASH}" <<'SQL'
INSERT INTO admin_users (username, email, password_hash, role, is_active)
VALUES (:'ADMIN_USER_V', :'ADMIN_EMAIL_V', :'HASH_V', 'admin', true)
ON CONFLICT (username) DO UPDATE
  SET password_hash = EXCLUDED.password_hash,
      email         = EXCLUDED.email,
      is_active     = true,
      updated_at    = CURRENT_TIMESTAMP;
SQL

if [[ ! -f "${ADMIN_ENV_FILE}" ]]; then
  umask 077
  cat > "${ADMIN_ENV_FILE}" <<EOF
ADMIN_URL=https://${DOMAIN}
ADMIN_USERNAME=${ADMIN_USER}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF
  chmod 600 "${ADMIN_ENV_FILE}"
fi
log "admin upserted"

# ----- 8. Fill the connect doc --------------------------------------------------
log "8/9 fill connect doc -> ${HANDOFF_DOC}"
mkdir -p "${HANDOFF_DIR}"; chmod 700 "${HANDOFF_DIR}"
MCP_AUTH_TOKEN="$(grep '^MCP_AUTH_TOKEN=' "${ENV_FILE}" | cut -d= -f2-)"

# Strip the top template comment block (everything up to and including the closing -->),
# then substitute placeholders.
umask 077
awk 'f{print} /-->/{f=1}' "${TEMPLATE_DOC}" > "${HANDOFF_DOC}"
# If no comment block was found (awk produced nothing), fall back to full file.
[[ -s "${HANDOFF_DOC}" ]] || cp "${TEMPLATE_DOC}" "${HANDOFF_DOC}"

# Substitute with a safe delimiter; token/password contain only url/base64-safe chars.
sed -i \
  -e "s#{{MCP_URL}}#https://${DOMAIN}/mcp#g" \
  -e "s#{{DASHBOARD_URL}}#https://${DOMAIN}#g" \
  -e "s#{{TOKEN}}#${MCP_AUTH_TOKEN}#g" \
  -e "s#{{ADMIN_USER}}#${ADMIN_USER}#g" \
  -e "s#{{ADMIN_PASSWORD}}#${ADMIN_PASSWORD}#g" \
  "${HANDOFF_DOC}"
chmod 600 "${HANDOFF_DOC}"

LEFTOVER="$(grep -c '{{' "${HANDOFF_DOC}" || true)"
[[ "${LEFTOVER}" == "0" ]] || fail "connect doc still has ${LEFTOVER} '{{' placeholders"
log "connect doc filled (0 leftover placeholders)"

# ----- 9. Smoke gate ------------------------------------------------------------
log "9/9 smoke gate"
SMOKE_OK=1
smoke() {  # name expected actual
  if [[ "$2" == "$3" ]]; then echo "  [PASS] $1: $3"; else echo "  [FAIL] $1: got $3, expected $2"; SMOKE_OK=0; fi
}

INIT_BODY='{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"smoke","version":"1.0"}}}'

# (a) public /healthz 200 via real domain
hz=$(curl -s -o /dev/null -w '%{http_code}' --resolve "${DOMAIN}:443:${EXPECTED_IP}" "https://${DOMAIN}/healthz")
smoke "healthz (public 200)" "200" "${hz}"

# (b) /mcp no-token 401
n401=$(curl -s -o /dev/null -w '%{http_code}' --resolve "${DOMAIN}:443:${EXPECTED_IP}" \
  -X POST "https://${DOMAIN}/mcp" -H 'Content-Type: application/json' \
  -H 'Accept: application/json, text/event-stream' -d "${INIT_BODY}")
smoke "mcp no-token (401)" "401" "${n401}"

# (c) /mcp with-token 200
y200=$(curl -s -o /dev/null -w '%{http_code}' --resolve "${DOMAIN}:443:${EXPECTED_IP}" \
  -X POST "https://${DOMAIN}/mcp" -H "Authorization: Bearer ${MCP_AUTH_TOKEN}" \
  -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' -d "${INIT_BODY}")
smoke "mcp with-token (200)" "200" "${y200}"

# (d) /api/auth/login with admin creds 200 (direct to backend container)
login=$(curl -s -o /dev/null -w '%{http_code}' -X POST "http://127.0.0.1:${BACKEND_PORT}/api/auth/login" \
  -H 'Content-Type: application/json' \
  -d "{\"username\":\"${ADMIN_USER}\",\"password\":$(node -e 'console.log(JSON.stringify(process.argv[1]))' "${ADMIN_PASSWORD}")}")
smoke "admin login (200)" "200" "${login}"

# (e) POST /api/v2/sessions/start -> 201 + non-null data (direct to mcp container)
SESS_RESP="$(curl -s -X POST "http://127.0.0.1:${MCP_PORT}/api/v2/sessions/start" -H 'Content-Type: application/json' -d '{}')"
SESS_CODE="$(curl -s -o /dev/null -w '%{http_code}' -X POST "http://127.0.0.1:${MCP_PORT}/api/v2/sessions/start" -H 'Content-Type: application/json' -d '{}')"
HAS_DATA="$(printf '%s' "${SESS_RESP}" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const j=JSON.parse(s);process.stdout.write(j&&j.data&&j.data.session_id?"yes":"no")}catch(e){process.stdout.write("no")}})')"
smoke "sessions/start (201)" "201" "${SESS_CODE}"
smoke "sessions/start data non-null" "yes" "${HAS_DATA}"

# (f) dual_write_config = 5 rows
DWC="$(docker exec "mandrel-${H}-postgres" psql -U mandrel -d mandrel -tAc 'SELECT count(*) FROM dual_write_config;' | tr -d '[:space:]')"
smoke "dual_write_config rows (5)" "5" "${DWC}"

echo "----------------------------------------------------------------"
if [[ "${SMOKE_OK}" == "1" ]]; then
  log "PROVISIONED OK — handoff: ${HANDOFF_DOC}"
  echo "RESULT:${H}:provisioned"
else
  log "SMOKE FAILED — see [FAIL] lines above. Stack is up; handoff: ${HANDOFF_DOC}"
  echo "RESULT:${H}:smoke-failed"
  exit 1
fi
