/**
 * Deploy-smoke litter exclusion + duration-calc contract test (task bc819ae5)
 *
 * WHAT THIS PROVES (drives REAL Postgres — the disposable migrated CI DB):
 *
 *  The fleet deploy smoke (scripts/fleet-deploy.sh) POSTs /api/v2/sessions/start
 *  to every instance on every deploy to prove the session write-path is alive.
 *  That used to leave an untitled, never-ended `sessions` row PER INSTANCE PER
 *  DEPLOY — litter that polluted the sessions list + session stats fleet-wide.
 *
 *  The fix marks those rows with agent_type = 'deploy-smoke' and excludes the
 *  marker from EVERY analytics read path. This test is the executable fuse:
 *
 *    1. v_session_summaries (feeds the sessions LIST, single detail, compare)
 *       does NOT contain a 'deploy-smoke' session, but DOES contain a normal one.
 *    2. SessionStatsService.getSessionStatsEnhanced excludes 'deploy-smoke' from
 *       BOTH the session count and the top-tags aggregation (it reads
 *       `FROM sessions` directly, bypassing the view — so it needs its own guard).
 *    3. DURATION-CALC: an UNCLOSED session (ended_at IS NULL) yields a SANE
 *       duration via COALESCE(ended_at, NOW()) — finite, >= 0, NOT null/negative.
 *
 *  It FAILS on pre-fix code: without the migration-048 WHERE clause the smoke row
 *  appears in the view (assertion 1), and without the SessionStatsService guard
 *  the smoke row is counted in stats (assertion 2).
 *
 * DB target: the disposable throwaway DB provisioned + migrated by scripts/ci.sh
 * (DATABASE_* env point at it). Runs as part of the full vitest suite.
 */

import { describe, test, expect, beforeAll, afterAll, vi } from 'vitest';

// Restore real crypto so each created session gets a distinct UUID (the global
// vitest.setup.ts mocks randomUUID with a resettable counter).
vi.unmock('crypto');
vi.unmock('node:crypto');

import { randomUUID } from 'node:crypto';
import { db } from '../config/database.js';
import { SessionStatsService } from '../services/session/domain/stats/SessionStatsService.js';
import { DEPLOY_SMOKE_AGENT_TYPE } from '../services/session/types.js';

const STAMP = Date.now();
const PROJECT_NAME = `smoke-litter-P-${STAMP}`;
const NORMAL_TAG = `litter-normal-${STAMP}`;
const SMOKE_TAG = `litter-smoke-${STAMP}`;

let projectId: string;
let normalSessionId: string;
let smokeSessionId: string;
let unclosedSessionId: string;

/**
 * Insert a session row directly. agent_type drives the marker; ended_at = null
 * leaves it "unclosed". display_id is auto-generated by a BEFORE INSERT trigger.
 */
async function insertSession(opts: {
  id: string;
  agentType: string;
  endedAtSql: string; // e.g. 'NOW()' or 'NULL'
  startedAtSql: string; // e.g. "NOW() - interval '30 minutes'"
  tags: string[];
}): Promise<void> {
  await db.query(
    `INSERT INTO sessions (id, project_id, agent_type, started_at, ended_at, status, tags)
     VALUES ($1, $2, $3, ${opts.startedAtSql}, ${opts.endedAtSql}, 'active', $4)`,
    [opts.id, projectId, opts.agentType, opts.tags]
  );
}

beforeAll(async () => {
  projectId = (
    await db.query(
      `INSERT INTO projects (name, description) VALUES ($1, 'smoke litter test') RETURNING id`,
      [PROJECT_NAME]
    )
  ).rows[0].id;

  normalSessionId = randomUUID();
  smokeSessionId = randomUUID();
  unclosedSessionId = randomUUID();

  // A normal, closed session 30 min long.
  await insertSession({
    id: normalSessionId,
    agentType: 'claude-code',
    startedAtSql: "NOW() - interval '30 minutes'",
    endedAtSql: 'NOW()',
    tags: [NORMAL_TAG],
  });

  // A deploy-smoke session — the litter we must exclude. Also UNCLOSED (the smoke
  // never ended it pre-fix), so it doubles as a litter+unclosed case.
  await insertSession({
    id: smokeSessionId,
    agentType: DEPLOY_SMOKE_AGENT_TYPE,
    startedAtSql: "NOW() - interval '5 minutes'",
    endedAtSql: 'NULL',
    tags: [SMOKE_TAG],
  });

  // A normal UNCLOSED session for the duration-calc assertion (started 45 min ago).
  await insertSession({
    id: unclosedSessionId,
    agentType: 'claude-code',
    startedAtSql: "NOW() - interval '45 minutes'",
    endedAtSql: 'NULL',
    tags: [NORMAL_TAG],
  });
});

afterAll(async () => {
  try {
    await db.query('DELETE FROM sessions WHERE project_id = $1', [projectId]);
    await db.query('DELETE FROM projects WHERE id = $1', [projectId]);
  } catch {
    /* ignore */
  }
  await db.end();
});

describe('deploy-smoke litter exclusion (task bc819ae5)', () => {
  test('v_session_summaries EXCLUDES deploy-smoke, KEEPS normal sessions', async () => {
    const rows = (
      await db.query(
        `SELECT id, agent_type FROM v_session_summaries WHERE project_id = $1`,
        [projectId]
      )
    ).rows as Array<{ id: string; agent_type: string }>;

    const ids = new Set(rows.map((r) => r.id));
    // Normal + unclosed-normal are present; smoke is gone.
    expect(ids.has(normalSessionId)).toBe(true);
    expect(ids.has(unclosedSessionId)).toBe(true);
    expect(ids.has(smokeSessionId)).toBe(false);
    // No row of the smoke marker leaks through the view at all.
    expect(rows.some((r) => r.agent_type === DEPLOY_SMOKE_AGENT_TYPE)).toBe(false);
  });

  test('getSessionStatsEnhanced EXCLUDES deploy-smoke from count and top tags', async () => {
    const stats = await SessionStatsService.getSessionStatsEnhanced({ projectId });

    // Exactly the 2 non-smoke sessions are counted (normal + unclosed-normal).
    expect(stats.overall.totalSessions).toBe(2);
    // Top tags include the normal tag but NEVER the smoke tag.
    expect(stats.topTags).toContain(NORMAL_TAG);
    expect(stats.topTags).not.toContain(SMOKE_TAG);
  });

  test('duration-calc: an UNCLOSED session yields a sane (finite, >= 0) duration', async () => {
    const row = (
      await db.query(
        `SELECT duration_minutes FROM v_session_summaries WHERE id = $1`,
        [unclosedSessionId]
      )
    ).rows[0] as { duration_minutes: string | number } | undefined;

    expect(row).toBeDefined();
    const minutes = Number(row!.duration_minutes);
    expect(Number.isFinite(minutes)).toBe(true);
    expect(minutes).not.toBeNaN();
    // ~45 minutes elapsed and climbing; must be positive (COALESCE(ended_at, NOW())),
    // never null/negative. Generous bounds to avoid clock-flake.
    expect(minutes).toBeGreaterThan(40);
    expect(minutes).toBeLessThan(120);
  });
});
